### ISSUE TITLE
gitinstall.bat is not working on Windows11

### ISSUE THREAD

**Issue by Anertz** [suginomoto/.minecraft#1]
ネットワーク パスが見つかりません。
'it-2.47.1-64-bit.exe' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ing' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'mmand' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ードが終了しました。' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
続行するには何かキーを押してください . . .

**Comment by suginomoto** [comment]
仕様を変更し、改善しました。
